-- Idempotent seed: only insert if wines table is empty
INSERT INTO wines (name, winery, country, region, grape_variety, wine_type, sweetness, body, acidity, tannin, flavor_notes, food_pairing, price, rating, image_url, description)
SELECT * FROM (VALUES
    ('Würzburger Stein Riesling Kabinett',
     'Bürgerspital', 'Germany', 'Franken', 'Riesling', 'White', 'Semi-Dry', 'Light', 'High', 'Low',
     'Green apple, citrus, mineral, slight floral notes',
     'Grilled fish, asparagus, light cheeses',
     12.90, 4.2, '/images/wuerzburger-stein.jpg',
     'A classic Franken Riesling from one of Germany''s most historic wine estates. Elegant and refreshing with a signature mineral backbone.'),

    ('Grauburgunder Trocken',
     'Weingut Knipser', 'Germany', 'Pfalz', 'Grauburgunder', 'White', 'Dry', 'Medium', 'Medium', 'Low',
     'Ripe pear, quince, white peach, subtle spice',
     'Grilled chicken, cream pasta, brie',
     10.50, 4.0, '/images/grauburgunder-knipser.jpg',
     'A wonderfully balanced Pinot Gris from the Pfalz, showing generous stone fruit character and a clean, dry finish.'),

    ('Chianti Classico Riserva',
     'Castello di Volpaia', 'Italy', 'Toscana', 'Sangiovese', 'Red', 'Dry', 'Medium', 'High', 'Medium',
     'Cherry, dried herbs, leather, tobacco, earthy notes',
     'Pasta with meat sauce, bistecca fiorentina, aged pecorino',
     19.90, 4.4, '/images/chianti-classico.jpg',
     'A benchmark Chianti Classico Riserva from the elevated vineyards of Radda in Chianti. Full of character and complexity.'),

    ('Primitivo di Manduria',
     'Feudi di San Marzano', 'Italy', 'Puglia', 'Primitivo', 'Red', 'Dry', 'Full', 'Medium', 'Medium',
     'Dark cherry, blackberry, chocolate, vanilla, spice',
     'Grilled meats, barbecue, hard cheeses, lamb',
     9.90, 4.1, '/images/primitivo-manduria.jpg',
     'Rich and generous Primitivo from Puglia''s sun-drenched south. Deep colour, velvety tannins and a long, warm finish.'),

    ('Côtes du Rhône Rouge',
     'E. Guigal', 'France', 'Rhone', 'Shiraz', 'Red', 'Dry', 'Medium', 'Medium', 'Medium',
     'Black pepper, red berry, olive, thyme, smoky notes',
     'Pasta, pizza, grilled sausages, charcuterie',
     11.90, 4.0, '/images/cotes-du-rhone-guigal.jpg',
     'An iconic Côtes du Rhône from the legendary house of Guigal. Approachable, food-friendly and full of Southern Rhône character.'),

    ('Provence Rosé Cuvée',
     'Château Miraval', 'France', 'Provence', 'Cinsault', 'Rosé', 'Dry', 'Light', 'High', 'Low',
     'Fresh strawberry, peach, rose petal, citrus zest',
     'Grilled seafood, salads, charcuterie, goat cheese',
     16.90, 4.3, '/images/miraval-rose.jpg',
     'The iconic Provençal rosé co-created by Brad Pitt and Angelina Jolie. Pale salmon colour, delicate and refreshing.'),

    ('Chardonnay Grand Cru Chablis',
     'Domaine William Fèvre', 'France', 'Bourgogne', 'Chardonnay', 'White', 'Dry', 'Full', 'High', 'Low',
     'Green apple, flint, oyster shell, lemon, toasted oak',
     'Oysters, lobster, scallops, turbot',
     29.90, 4.6, '/images/chablis-fevre.jpg',
     'A magnificent Grand Cru Chablis from one of the appellation''s finest producers. Intense mineral expression with great aging potential.'),

    ('Grüner Veltliner Federspiel',
     'Domäne Wachau', 'Austria', 'Wachau', 'Grüner Veltliner', 'White', 'Dry', 'Light', 'High', 'Low',
     'White pepper, green herbs, citrus, stone fruit',
     'Wiener Schnitzel, white fish, vegetable dishes',
     11.90, 4.1, '/images/gruner-veltliner-wachau.jpg',
     'A classic Wachau Federspiel from the renowned Domäne Wachau. Light, crisp and perfectly expressive of the Grüner Veltliner grape.'),

    ('Cabernet Sauvignon Reserva',
     'Concha y Toro', 'Chile', 'Maipo Valley', 'Cabernet Sauvignon', 'Red', 'Dry', 'Full', 'Medium', 'High',
     'Blackcurrant, cedar, dark chocolate, green pepper, tobacco',
     'Steak, roast lamb, beef stew, hard cheeses',
     8.90, 3.9, '/images/concha-y-toro-cab.jpg',
     'Chile''s most celebrated wine producer delivers a classic Maipo Valley Cabernet Sauvignon with confident structure and excellent value.'),

    ('Merlot Napa Valley',
     'Duckhorn Vineyards', 'USA', 'California', 'Merlot', 'Red', 'Dry', 'Full', 'Medium', 'Medium',
     'Plum, black cherry, mocha, chocolate, silky tannins',
     'Roast duck, beef tenderloin, mushroom risotto',
     24.90, 4.5, '/images/duckhorn-merlot.jpg',
     'Duckhorn''s legendary Napa Valley Merlot set the benchmark for the variety in California. Luscious, velvety and beautifully crafted.'),

    ('Shiraz Barossa Valley',
     'Penfolds Bin 28', 'Australia', 'Barossa Valley', 'Shiraz', 'Red', 'Dry', 'Full', 'Medium', 'High',
     'Dark fruit, leather, dark chocolate, eucalyptus, spice',
     'BBQ ribs, kangaroo steak, aged cheddar',
     22.90, 4.4, '/images/penfolds-bin28.jpg',
     'A celebrated Australian Shiraz from one of Penfolds'' iconic Bin series. Rich, bold and unmistakably Barossa in character.'),

    ('Südtiroler Lagrein Dunkel',
     'Kellerei Bozen', 'Italy', 'Sudtirol', 'Lagrein', 'Red', 'Dry', 'Full', 'Medium', 'Medium',
     'Dark cherry, blueberry, bitter chocolate, violet, earthy',
     'Venison, beef goulash, hard mountain cheeses',
     14.50, 4.2, '/images/lagrein-bozen.jpg',
     'Lagrein is South Tyrol''s most characterful red grape. This example from the Bozen cooperative is deep, complex and distinctly Alpine.'),

    ('Riesling Eiswein',
     'Weingut Robert Weil', 'Germany', 'Rheingau', 'Riesling', 'White', 'Sweet', 'Light', 'High', 'Low',
     'Apricot, peach, honey, candied orange peel, tropical fruit',
     'Foie gras, blue cheese, fruit tarts, crème brûlée',
     34.90, 4.8, '/images/robert-weil-eiswein.jpg',
     'A breathtaking Eiswein from the legendary Robert Weil estate. Concentrated sweetness perfectly balanced by razor-sharp Riesling acidity.'),

    ('Sauvignon Blanc Marlborough',
     'Cloudy Bay', 'New Zealand', 'Marlborough', 'Sauvignon Blanc', 'White', 'Dry', 'Light', 'High', 'Low',
     'Passion fruit, grapefruit, cut grass, gooseberry, elderflower',
     'Grilled fish, Thai cuisine, asparagus, goat cheese salad',
     15.90, 4.3, '/images/cloudy-bay-sauv.jpg',
     'The wine that put Marlborough on the world wine map. Cloudy Bay''s Sauvignon Blanc remains the benchmark for New Zealand''s signature style.'),

    ('Weißburgunder Trocken',
     'Weingut Dr. Heger', 'Germany', 'Baden', 'Weißburgunder', 'White', 'Dry', 'Medium', 'Medium', 'Low',
     'White apple, almond, nectarine, cream, subtle mineral',
     'Grilled trout, chicken in cream sauce, mild cheeses',
     13.50, 4.0, '/images/weissburgunder-heger.jpg',
     'An elegant Pinot Blanc from Baden''s warmest wine region. Richer and rounder than Alsatian styles with a lovely creamy texture.'),

    ('Silvaner Kabinett',
     'Weingut Wirsching', 'Germany', 'Franken', 'Silvaner', 'White', 'Semi-Dry', 'Light', 'Medium', 'Low',
     'Herbs, earthy mineral, green apple, mild citrus',
     'White asparagus, river fish, light vegetarian dishes',
     11.20, 3.8, '/images/silvaner-wirsching.jpg',
     'Silvaner is Franken''s soul grape. This Kabinett is understated and food-friendly with a distinctive earthy minerality.'),

    ('Nero d''Avola Sicilia',
     'Donnafugata', 'Italy', 'Sicilia', 'Nero d''Avola', 'Red', 'Dry', 'Full', 'Medium', 'Medium',
     'Black cherry, dried fig, liquorice, tobacco, Mediterranean herbs',
     'Lamb with herbs, pasta al forno, caciocavallo cheese',
     12.50, 4.1, '/images/nero-davola-donnafugata.jpg',
     'Sicily''s flagship red grape at its most expressive. Donnafugata brings structure and elegance to this sun-drenched Nero d''Avola.'),

    ('Chenin Blanc Stellenbosch',
     'Ken Forrester Wines', 'South Africa', 'Stellenbosch', 'Chenin Blanc', 'White', 'Dry', 'Medium', 'High', 'Low',
     'Guava, pineapple, honeysuckle, quince, fresh hay',
     'Spicy Asian dishes, grilled prawns, pork belly',
     13.90, 4.2, '/images/chenin-blanc-forrester.jpg',
     'South Africa is Chenin Blanc''s adopted homeland, and Ken Forrester is its greatest champion. Vibrant, textured and complex.'),

    ('Riesling Spätlese Nahe',
     'Weingut Dönnhoff', 'Germany', 'Nahe', 'Riesling', 'White', 'Semi-Dry', 'Light', 'High', 'Low',
     'Ripe peach, apricot, floral, mineral, slate',
     'Spicy cuisine, duck with fruit sauce, blue cheese',
     18.50, 4.5, '/images/donnhoff-riesling.jpg',
     'Dönnhoff is one of Germany''s most revered Riesling producers. This Spätlese from the Nahe showcases the perfume and precision for which the estate is famous.'),

    ('Grauburgunder Spätburgunder Rosé',
     'Weingut Salwey', 'Germany', 'Baden', 'Grauburgunder', 'Rosé', 'Dry', 'Light', 'Medium', 'Low',
     'Wild strawberry, redcurrant, pomegranate, rose water',
     'Charcuterie, salmon tartare, grilled vegetables',
     14.80, 4.0, '/images/salwey-rose.jpg',
     'A sophisticated Baden Rosé from the Salwey estate. Pale copper in colour with delicate red berry fruit and a crisp dry finish.')
) AS v(name, winery, country, region, grape_variety, wine_type, sweetness, body, acidity, tannin, flavor_notes, food_pairing, price, rating, image_url, description)
WHERE NOT EXISTS (SELECT 1 FROM wines LIMIT 1);
